kind: Pod
apiVersion: v1
metadata:
  name: cm-env-var-pod-1
spec:
  containers:
    - name: env-var-configmap
      image: nginx
      volumeMounts:
        - name: myvol
          mountPath: /mydata
  volumes:  
    - name: myvol  
      configMap:
        name: game-config
