apiVersion: v1
kind: Pod
metadata:
  name: multi-cont2
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    command: ['/bin/bash', '-c', 'sleep 30']
  - name: alpine
    image: alpine
    command: ['sh', '-c', 'sleep 30']
