apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels: 
     app: tomcat
spec:
  schedulerName: my-scheduler       
  containers:
  - name: tomcat
    image: tomcat
    ports:
     - containerPort: 8080
