apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  nodeName: ip-172-31-46-225
  containers:     
   - name: myvolumes-container
     image: alpine
     imagePullPolicy: IfNotPresent
     command: ['sh', '-c', 'echo container 1 is running ; sleep 3600']
     volumeMounts:
      - name: pv
        mountPath: "/my-pvc-path"
  volumes:
   - name: pv
     persistentVolumeClaim:
       claimName: my-pvc
