kind: Pod
apiVersion: v1
metadata:
  name: sec-var-pod
spec:
  containers:
    - name: env-var-configmap
      image: nginx
      volumeMounts:
        - name: myvol
          mountPath: /mydata    
  volumes: 
    - name: myvol  
      secret:
        secretName: test-secret
