apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      name: kubeserve
      labels:
        app: kubeserve
    spec:
      tolerations:
        - key: per
          operator: "Equal"
          value: "police"
          effect: "NoSchedule"
      containers:
      - image: leaddevops/kubeserve:v1
        name: app

