apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-example
  labels:
    app: crashlooplearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashlooplearning
  template:
    metadata:
      labels:
        app: crashlooplearning
    spec:
      containers:
      - name: crashlooplearning
        image: saikishore789/pythonapp:v1
##        command: ["/bin/sh"]
##        args: ["-c", "python3 app1.py"]
        ports:
        - containerPort: 8000