apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
#  strategy:
#    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
#        kubernetes.io/hostname: minikube-m02
        foo: bar
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80